"""麻将核心逻辑：牌型定义、洗牌发牌、状态序列化与胡牌判定。"""

from .game import (
    declare_draw,
    declare_win,
    deal_tiles,
    discard_tile,
    draw_tile,
    new_game,
    shuffle_tiles,
    waits_for,
)
from .state import STATE_VERSION, GameState, PlayerState, StateError
from .tiles import (
    ALL_CODES,
    COPIES_PER_KIND,
    HONOR_NAMES,
    KIND_COUNT,
    SUIT_NAMES,
    SUITS,
    TERMINAL_HONOR_CODES,
    TOTAL_TILES,
    Tile,
    build_wall,
    parse_tile,
    sort_tiles,
    tile_index,
    tile_name,
    validate_codes,
)
from .win import (
    PATTERN_SEVEN_PAIRS,
    PATTERN_STANDARD,
    PATTERN_THIRTEEN_ORPHANS,
    is_valid_meld,
    is_win,
    win_patterns,
    winning_tiles,
)

__all__ = [
    "ALL_CODES",
    "COPIES_PER_KIND",
    "GameState",
    "HONOR_NAMES",
    "KIND_COUNT",
    "PATTERN_SEVEN_PAIRS",
    "PATTERN_STANDARD",
    "PATTERN_THIRTEEN_ORPHANS",
    "PlayerState",
    "STATE_VERSION",
    "SUIT_NAMES",
    "SUITS",
    "StateError",
    "TERMINAL_HONOR_CODES",
    "TOTAL_TILES",
    "Tile",
    "build_wall",
    "declare_draw",
    "declare_win",
    "deal_tiles",
    "discard_tile",
    "draw_tile",
    "is_valid_meld",
    "is_win",
    "new_game",
    "parse_tile",
    "shuffle_tiles",
    "sort_tiles",
    "tile_index",
    "tile_name",
    "validate_codes",
    "waits_for",
    "win_patterns",
    "winning_tiles",
]
